// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
// VCS coverage exclude_file
module ram_2x289(	// src/main/scala/chisel3/util/Queue.scala:73:91
  input          R0_addr,
                 R0_en,
                 R0_clk,
  output [288:0] R0_data,
  input          W0_addr,
                 W0_en,
                 W0_clk,
  input  [288:0] W0_data
);

  reg [288:0] Memory[0:1];	// src/main/scala/chisel3/util/Queue.scala:73:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Queue.scala:73:91
    if (W0_en & 1'h1)	// src/main/scala/chisel3/util/Queue.scala:73:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/chisel3/util/Queue.scala:73:91
    reg [319:0] _RANDOM_MEM;	// src/main/scala/chisel3/util/Queue.scala:73:91
    initial begin	// src/main/scala/chisel3/util/Queue.scala:73:91
      `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:73:91
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/chisel3/util/Queue.scala:73:91
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          for (logic [8:0] j = 9'h0; j < 9'h140; j += 9'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:73:91
          end
          Memory[i[0]] = _RANDOM_MEM[288:0];	// src/main/scala/chisel3/util/Queue.scala:73:91
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 289'bx;	// src/main/scala/chisel3/util/Queue.scala:73:91
endmodule

module Queue2_AxiWriteData(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input          clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                 reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output         io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [255:0] io_enq_bits_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [31:0]  io_enq_bits_strb,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input          io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [255:0] io_deq_bits_data,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output         io_deq_bits_last,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [31:0]  io_deq_bits_strb	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  wire [288:0] _ram_ext_R0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg          wrap;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire         ptr_match = wrap == wrap_1;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:77:33
  wire         empty = ptr_match & ~maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :78:{25,28}
  wire         full = ptr_match & maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :79:24
  wire         do_enq = ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:79:24, :103:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      wrap <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      wrap_1 <= 1'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
    end
    else begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic do_deq = io_deq_ready & ~empty;	// src/main/scala/chisel3/util/Queue.scala:78:25, :102:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap <= wrap - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        wrap_1 <= wrap_1 - 1'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (~(do_enq == do_deq))	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_2x289 ram_ext (	// src/main/scala/chisel3/util/Queue.scala:73:91
    .R0_addr (wrap_1),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (wrap),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    .W0_clk  (clock),
    .W0_data ({io_enq_bits_data, 1'h1, io_enq_bits_strb})	// src/main/scala/chisel3/util/Queue.scala:73:91
  );	// src/main/scala/chisel3/util/Queue.scala:73:91
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :79:24, :103:19
  assign io_deq_valid = ~empty;	// src/main/scala/chisel3/util/Queue.scala:60:7, :78:25, :102:19
  assign io_deq_bits_data = _ram_ext_R0_data[288:33];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_last = _ram_ext_R0_data[32];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_strb = _ram_ext_R0_data[31:0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
endmodule

module DBus2AxiV2(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  input          clock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
                 reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
                 io_dbus_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_dbus_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input          io_dbus_write,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input  [31:0]  io_dbus_pc,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
                 io_dbus_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
                 io_dbus_adrx,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input  [5:0]   io_dbus_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input  [255:0] io_dbus_wdata,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input  [31:0]  io_dbus_wmask,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [255:0] io_dbus_rdata,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input          io_axi_write_addr_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_axi_write_addr_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [31:0]  io_axi_write_addr_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [2:0]   io_axi_write_addr_bits_prot,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [5:0]   io_axi_write_addr_bits_id,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [7:0]   io_axi_write_addr_bits_len,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [2:0]   io_axi_write_addr_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [1:0]   io_axi_write_addr_bits_burst,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_axi_write_addr_bits_lock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [3:0]   io_axi_write_addr_bits_cache,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
                 io_axi_write_addr_bits_qos,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
                 io_axi_write_addr_bits_region,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input          io_axi_write_data_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_axi_write_data_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [255:0] io_axi_write_data_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_axi_write_data_bits_last,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [31:0]  io_axi_write_data_bits_strb,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_axi_write_resp_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input          io_axi_write_resp_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input  [5:0]   io_axi_write_resp_bits_id,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input  [1:0]   io_axi_write_resp_bits_resp,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input          io_axi_read_addr_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_axi_read_addr_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [31:0]  io_axi_read_addr_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [2:0]   io_axi_read_addr_bits_prot,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [5:0]   io_axi_read_addr_bits_id,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [7:0]   io_axi_read_addr_bits_len,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [2:0]   io_axi_read_addr_bits_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [1:0]   io_axi_read_addr_bits_burst,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_axi_read_addr_bits_lock,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [3:0]   io_axi_read_addr_bits_cache,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
                 io_axi_read_addr_bits_qos,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
                 io_axi_read_addr_bits_region,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_axi_read_data_ready,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input          io_axi_read_data_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input  [255:0] io_axi_read_data_bits_data,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input  [5:0]   io_axi_read_data_bits_id,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input  [1:0]   io_axi_read_data_bits_resp,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  input          io_axi_read_data_bits_last,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output         io_fault_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
                 io_fault_bits_write,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
  output [31:0]  io_fault_bits_addr,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
                 io_fault_bits_epc	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:44:14
);

  wire         _wdataQueue_io_enq_ready;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:66:26
  reg          waddrFired;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:57:27
  wire         io_axi_write_addr_valid_0 = ~waddrFired & io_dbus_valid & io_dbus_write;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:57:27, :58:{30,42,59}
  reg          wdataFired;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:65:27
  wire         wdataQueue_io_enq_valid = ~wdataFired & io_dbus_valid & io_dbus_write;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:65:27, :67:{30,42,59}
  reg          wrespReceived;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:73:30
  wire         io_axi_write_resp_ready_0 = ~wrespReceived & io_dbus_valid & io_dbus_write;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:73:30, :74:{30,45,62}
  wire         _waddrFired_T = io_axi_write_addr_ready & io_axi_write_addr_valid_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:58:{42,59}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire         _wdataFired_T = _wdataQueue_io_enq_ready & wdataQueue_io_enq_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:66:26, :67:{42,59}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire         _wrespReceived_T = io_axi_write_resp_ready_0 & io_axi_write_resp_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:74:{45,62}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire         writeFinished =
    (_waddrFired_T | waddrFired) & (_wdataFired_T | wdataFired)
    & (_wrespReceived_T | wrespReceived);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:57:27, :65:27, :73:30, :76:{47,62}, :77:{47,62}, :78:47, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  reg          raddrFired;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:94:27
  wire         io_axi_read_addr_valid_0 = ~raddrFired & io_dbus_valid & ~io_dbus_write;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:94:27, :95:{29,41,58,61}
  reg          rdataReceived_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:102:30
  reg  [255:0] rdataReceived_bits;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:102:30
  wire         io_axi_read_data_ready_0 =
    ~rdataReceived_valid & io_dbus_valid & ~io_dbus_write;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:95:61, :102:30, :104:{7,28,45}
  wire         _raddrFired_T = io_axi_read_addr_ready & io_axi_read_addr_valid_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:95:{41,58}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire         _readNext_T = io_axi_read_data_ready_0 & io_axi_read_data_valid;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:104:{28,45}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire         readFinished =
    (_raddrFired_T | raddrFired) & (_readNext_T | rdataReceived_valid);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:94:27, :102:30, :106:{45,60}, :107:45, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  reg  [255:0] readNext;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:118:25
  always @(posedge clock) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
    if (reset) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
      waddrFired <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:57:27
      wdataFired <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:65:27
      wrespReceived <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:73:30
      raddrFired <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:94:27
      rdataReceived_valid <= 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:102:30
      rdataReceived_bits <= 256'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:102:30
      readNext <= 256'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:118:25
    end
    else begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
      waddrFired <= ~writeFinished & (_waddrFired_T | waddrFired);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:57:27, :76:62, :77:62, src/main/scala/chisel3/util/Mux.scala:130:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      wdataFired <= ~writeFinished & (_wdataFired_T | wdataFired);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:65:27, :76:62, :77:62, src/main/scala/chisel3/util/Mux.scala:130:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      wrespReceived <= ~writeFinished & (_wrespReceived_T | wrespReceived);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:73:30, :76:62, :77:62, src/main/scala/chisel3/util/Mux.scala:130:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      raddrFired <= ~readFinished & (_raddrFired_T | raddrFired);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:94:27, :106:60, src/main/scala/chisel3/util/Mux.scala:130:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      rdataReceived_valid <= ~readFinished & (_readNext_T | rdataReceived_valid);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:102:30, :106:60, src/main/scala/chisel3/util/Mux.scala:130:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      if (readFinished) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:106:60
        rdataReceived_bits <= 256'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:102:30
        readNext <= _readNext_T ? io_axi_read_data_bits_data : rdataReceived_bits;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:102:30, :118:25, :121:10, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      end
      else if (_readNext_T)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        rdataReceived_bits <= io_axi_read_data_bits_data;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:102:30
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
      `FIRRTL_BEFORE_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
      automatic logic [31:0] _RANDOM[0:16];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
      `ifdef INIT_RANDOM_PROLOG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
        `INIT_RANDOM_PROLOG_	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
        for (logic [4:0] i = 5'h0; i < 5'h11; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
        end	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
        waddrFired = _RANDOM[5'h0][0];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :57:27
        wdataFired = _RANDOM[5'h0][1];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :57:27, :65:27
        wrespReceived = _RANDOM[5'h0][2];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :57:27, :73:30
        raddrFired = _RANDOM[5'h0][3];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :57:27, :94:27
        rdataReceived_valid = _RANDOM[5'h0][4];	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :57:27, :102:30
        rdataReceived_bits =
          {_RANDOM[5'h0][31:5],
           _RANDOM[5'h1],
           _RANDOM[5'h2],
           _RANDOM[5'h3],
           _RANDOM[5'h4],
           _RANDOM[5'h5],
           _RANDOM[5'h6],
           _RANDOM[5'h7],
           _RANDOM[5'h8][4:0]};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :57:27, :102:30
        readNext =
          {_RANDOM[5'h8][31:5],
           _RANDOM[5'h9],
           _RANDOM[5'hA],
           _RANDOM[5'hB],
           _RANDOM[5'hC],
           _RANDOM[5'hD],
           _RANDOM[5'hE],
           _RANDOM[5'hF],
           _RANDOM[5'h10][4:0]};	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :102:30, :118:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
      `FIRRTL_AFTER_INITIAL	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue2_AxiWriteData wdataQueue (	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:66:26
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_wdataQueue_io_enq_ready),
    .io_enq_valid     (wdataQueue_io_enq_valid),	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:67:{42,59}
    .io_enq_bits_data (io_dbus_wdata),
    .io_enq_bits_strb (io_dbus_wmask),
    .io_deq_ready     (io_axi_write_data_ready),
    .io_deq_valid     (io_axi_write_data_valid),
    .io_deq_bits_data (io_axi_write_data_bits_data),
    .io_deq_bits_last (io_axi_write_data_bits_last),
    .io_deq_bits_strb (io_axi_write_data_bits_strb)
  );	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:66:26
  assign io_dbus_ready = io_dbus_write ? writeFinished : readFinished;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :76:62, :77:62, :106:60, :127:23
  assign io_dbus_rdata = readNext;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :118:25
  assign io_axi_write_addr_valid = io_axi_write_addr_valid_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :58:{42,59}
  assign io_axi_write_addr_bits_addr = io_dbus_addr;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_write_addr_bits_prot = 3'h2;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_write_addr_bits_id = 6'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:49:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_write_addr_bits_len = 8'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:50:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_write_addr_bits_size =
    io_dbus_size[0]
      ? 3'h0
      : io_dbus_size[1]
          ? 3'h1
          : io_dbus_size[2]
              ? 3'h2
              : io_dbus_size[3]
                  ? 3'h3
                  : io_dbus_size[4] ? 3'h4 : io_dbus_size[5] ? 3'h5 : 3'h6;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:48:45
  assign io_axi_write_addr_bits_burst = 2'h1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:52:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_write_addr_bits_lock = 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_write_addr_bits_cache = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:54:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_write_addr_bits_qos = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:54:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_write_addr_bits_region = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:54:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_write_resp_ready = io_axi_write_resp_ready_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :74:{45,62}
  assign io_axi_read_addr_valid = io_axi_read_addr_valid_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :95:{41,58}
  assign io_axi_read_addr_bits_addr = io_dbus_addr;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_read_addr_bits_prot = 3'h2;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_read_addr_bits_id = 6'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:49:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_read_addr_bits_len = 8'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:50:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_read_addr_bits_size =
    io_dbus_size[0]
      ? 3'h0
      : io_dbus_size[1]
          ? 3'h1
          : io_dbus_size[2]
              ? 3'h2
              : io_dbus_size[3]
                  ? 3'h3
                  : io_dbus_size[4] ? 3'h4 : io_dbus_size[5] ? 3'h5 : 3'h6;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:48:45
  assign io_axi_read_addr_bits_burst = 2'h1;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:52:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_read_addr_bits_lock = 1'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_read_addr_bits_cache = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:54:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_read_addr_bits_qos = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:54:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_read_addr_bits_region = 4'h0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/bus/Axi.scala:54:12, home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_axi_read_data_ready = io_axi_read_data_ready_0;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :104:{28,45}
  assign io_fault_valid =
    io_dbus_valid
    & (io_dbus_write
         ? io_axi_write_resp_valid & (|io_axi_write_resp_bits_resp)
         : io_axi_read_data_valid & (|io_axi_read_data_bits_resp));	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7, :131:{35,41}, :133:{29,61}, :136:{28,59}
  assign io_fault_bits_write = io_dbus_write;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_fault_bits_addr = io_dbus_addr;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
  assign io_fault_bits_epc = io_dbus_pc;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:51:7
endmodule


// ----- 8< ----- FILE "verification/cover/layers-DBus2AxiV2-Verification_Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_DBus2AxiV2_Verification_Cover
`define layers_DBus2AxiV2_Verification_Cover	// <stdin>:17:5
`endif // layers_DBus2AxiV2_Verification_Cover	// <stdin>:17:5

// ----- 8< ----- FILE "verification/assume/layers-DBus2AxiV2-Verification_Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_DBus2AxiV2_Verification_Assume
`define layers_DBus2AxiV2_Verification_Assume	// <stdin>:16:5
`endif // layers_DBus2AxiV2_Verification_Assume	// <stdin>:16:5

// ----- 8< ----- FILE "verification/assert/layers-DBus2AxiV2-Verification_Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_DBus2AxiV2_Verification_Assert
`define layers_DBus2AxiV2_Verification_Assert	// <stdin>:15:5
bind DBus2AxiV2 DBus2AxiV2_Verification_Assert verification_Assert (
  .io_dbus_size  (io_dbus_size),
  ._GEN          (1'h1),
  .io_dbus_valid (io_dbus_valid),
  .reset         (reset),
  .clock         (clock)
);
`endif // layers_DBus2AxiV2_Verification_Assert	// <stdin>:15:5

// ----- 8< ----- FILE "verification/assert/DBus2AxiV2_Verification_Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module DBus2AxiV2_Verification_Assert(	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:9
  input [5:0] io_dbus_size,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:37
  input       _GEN,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:52
              io_dbus_valid,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:26
              reset,	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:9
              clock	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:9
);

  `ifndef SYNTHESIS	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:9
    always @(posedge clock) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:9
      if (~reset & io_dbus_valid
          & {1'h0,
             {1'h0, io_dbus_size[0]} + {1'h0, io_dbus_size[1]} + {1'h0, io_dbus_size[2]}}
          + {1'h0,
             {1'h0, io_dbus_size[3]} + {1'h0, io_dbus_size[4]}
               + {1'h0, io_dbus_size[5]}} != {2'h0, _GEN}) begin	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:{9,26,37,52}
        if (`ASSERT_VERBOSE_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:9
          $error("Assertion failed: Invalid dbus size=%d\n", io_dbus_size);	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:9
        if (`STOP_COND_)	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:9
          $fatal;	// home/ovs/vyges-test/coralnpu/hdl/chisel/src/coralnpu/DBus2Axi.scala:52:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

